In [141]:
import pandas as pd
import numpy as np

Q1. Pandas version
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [142]:
pd.__version__

'2.2.2'

Getting the data

In [143]:
df = pd.read_csv('../data/laptops.csv')

In [144]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

Q2. Records count:

How many records are in the dataset?

In [145]:
df.shape

(2160, 12)

Q3. Laptop brands:

How many laptop brands are presented in the dataset?

In [146]:
df['Brand'].nunique()

27

Q4. Missing values

How many columns in the dataset have missing values?

In [147]:
columns_with_missing = df.columns[df.isnull().any()].tolist()
num_columns_with_missing = len(columns_with_missing)
num_columns_with_missing

3

Q5. Maximum final price

What's the maximum final price of Dell notebooks in the dataset?

In [148]:
max_price_dell = df[df['Brand']=='Dell']['Final Price'].max()

In [149]:
print(max_price_dell)

3936.0


Q6. Median value of Screen

1. Find the median value of Screen column in the dataset.
2. Next, calculate the most frequent value of the same Screen column.
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
4. Now, calculate the median value of Screen once again.

In [150]:
screen_median_value = df['Screen'].median()
screen_median_value

15.6

In [151]:
screen_mode_value = df['Screen'].mode().iloc[0]
screen_mode_value

15.6

In [152]:
df['Screen'].isnull().sum()

4

In [153]:
df['Screen'] = df['Screen'].fillna(screen_mode_value)

In [154]:
screen_median_value = df['Screen'].median()
screen_median_value

15.6

In [155]:
df['Screen'].isnull().sum()

0

Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the sum of all the elements of the result?

In [156]:
df['Brand'].value_counts()

Brand
Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Primux                8
Deep Gaming           8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64

In [157]:
df_innjoo = df[df['Brand']=='Innjoo'][['RAM', 'Storage', 'Screen']]

In [158]:
df_innjoo

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [159]:
X = df_innjoo.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [160]:
XTX = np.dot(X.T, X)


In [161]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [162]:
XTX_inv = np.linalg.inv(XTX)

In [163]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [164]:
w = np.dot(np.dot(XTX_inv, X.T), y)

In [165]:
print(np.sum(w))

91.29988062995815
